### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by Bits001** [echolumaque/MedikTapp#10]
- [x] Register: Last Name, First Name, Email, Bday, Gender. Contact Number, Address
- [x] Booking na  may button na  “Book for someone else”
- [x] Promo notifications
~~Rename Schedules Tab to Appointments Tab~~
- [x] Validate muna yung available time before adding an appointment. One problem is if may kasabay mag query
- [x]  Notification tap feature that will go to appointment tab
- [x] Fix promos in mobile app when setting an appointment
- [x] Throw an error that the user already exists on Register endpoint
- [x] Logout function
  - Clear data upon logout
 ~~Clear appointments if it is more than current date by using Time Trigger (Azure Functions)~~ refer to: [this issue](https://github.com/echolumaque/MedikTapp/issues/11#:~:text=Completed%3A%20Create%20another%20endpoint%20to%20query%20completed%20appointment%20(use%20Time%20Trigger%20in%20Azure%20Functions))
- [x] Fix birthdate registration truncation
- [x] Fix app icon
~~filter combo box's margin~~
- [x] Fix entry search bar's margin
- [x] Fix spacing between service name and description on bookings and schedules tab's templates
- [x] Fix status bar color on onboarding page to match
- [x] Fix skip text's margin on onboarding page
- [x] Remove 'X' on entries
- [x] If an appointment is added, immediately update appointment tab's badge count
---
- [x] DB Changes:

Appointment Table :
Appointment Id | Patient Id | Service Id | Appointment Date | Booking Status | InBehalf | Prospect First Name |  Prospect Last Name | Prospect Age | Prospect Gender |  
|-|-|-|-|-|-|-|-|-|-|

Patients Table:
| Patient Id | First Name | LastName |  Email | Password | Birthday | Gender | Contact Number | Address | Age |
|-|-|-|-|-|-|-|-|-|-|

**Comment by jl-memosoft** [comment]
TODOS:

July 15, 2022
- [ ] Update Appointment and Patients table
- [ ] Create prospect on appointment. Make this a new page instead of popup
- [ ] Consume the newly created db on admin side

cc: @Bits001 @bern1101

**Comment by echolumaque** [comment]
TODOS:

July 15, 2022
- [x] Update Appointment and Patients table
- [x] Create prospect on appointment. Make this a new page instead of popup
- [ ] Consume the newly created db on admin side

cc: @Bits001 @bern1101
